resume_path: ''
batch_size: 16
epochs: 1000
loader_num_workers: 1
deterministic: False
sample_rate: 44100
win_length: 4096
hop_length: 1024
patch_length: 512
expand_factor: 12
learning_rate: 1.0e-3
weight_decay: 1.0e-6
optimizer: adam
deeper: False