MODEL_DIR: "./model/"
BATCH_SIZE: 1
EPOCHS: 200
LOADER_NUM_WORKERS: 4
SAMPLE_RATE: 44100
WIN_LENGTH: 4096
HOP_LENGTH: 1024
PATCH_LENGTH: 512
EXPAND_FACTOR: 12
LEARNING_RATE: 0.0001
WEIGHT_DECAY: 0.0001