resume_path: ''
batch_size: 16
epochs: 1000
loader_num_workers: 4
deterministic: True
precision: bf16
sample_rate: 44100
win_length: 4096
hop_length: 1024
patch_length: 512
expand_factor: 12
neglect_frequency: nyquist
learning_rate: 1.0e-04
weight_decay: 1.0e-08
optimizer: adam
deeper: True