name: svc

channels:
  - pytorch
  - conda-forge
  - nvidia

dependencies:
  - python=3.10.12
  - pip=23.2.1
  - ipykernel=6.26.0
  - numpy==1.22.4
  - scipy==1.7.3
  - nvidia::cudatoolkit=11.7.0
  - pytorch::pytorch=2.0.1
  - pytorch::torchaudio=2.0.2
  - pytorch-lightning=2.1.1
  - torchmetrics==1.2.0
  - pip:
    - pandas==2.1.3
    - scikit-learn==0.24.2
    - matplotlib==3.8.1
    - python-dotenv==1.0.0
    - musdb==0.4.0
    - librosa==0.10.1
    - git+https://github.com/moises-ai/moises-db.git
