name: svc

channels:
  - pytorch
  - conda-forge
  - nvidia

dependencies:
  - python=3.10.12
  - pip=23.2.1
  - nvidia::cudatoolkit=11.7.0
  - pytorch::pytorch=2.0.1
  - pytorch::torchaudio=2.0.2
  - numpy==1.22.4
  - scipy==1.7.3
  - pip:
    - musdb==0.4.0
    - python-dotenv==1.0.0
    - librosa==0.10.1
    - pandas==2.1.3
    - matplotlib==3.8.1
