name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        python-version:
          - "3.10"
        os:
          - ubuntu-latest
          # - windows-latest
          # - macOS-latest

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup xvfb (Linux)
        if: runner.os == 'Linux'
        run: sudo apt update && apt install -y xvfb x11-utils libxkbcommon-x11-0 ffmpeg libsm6 libxext6
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: 1.8.2
      - name: Install Dependencies
        run: poetry install
        shell: bash
      - name: Test with Pytest
        run: poetry run pytest --cov-report=xml
        shell: bash