name: Deployment

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  doc:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  - name: Build and publish to pypi
    uses: JRubics/poetry-publish@v2.0
    with:
      python_version: "3.10.12"
      poetry_version: "==1.8.2"
      pypi_token: ${{ secrets.PYPI_TOKEN }}